#!/bin/sh

# Enable on boot
/etc/init.d/wrtbwmon enable

# Configure our cron
echo 'Updating crontab'
crontab -u root -l | grep -v "wrtbwmon" > /tmp/crontab.tmp
echo "* * * * * /usr/sbin/wrtbwmon update /tmp/usage.db" >> /tmp/crontab.tmp
#echo "*/5 * * * * /usr/sbin/wrtbwmon publish /tmp/usage.db /tmp/usage.htm" >> /tmp/crontab.tmp
crontab -u root /tmp/crontab.tmp
rm -f /tmp/crontab.tmp
/etc/init.d/cron reload

# Symlink to our webdir
if [ -d "/var/www/html" ]; then
  ln -s /tmp/usage.htm /var/www/html/usage.htm
elif [ -d "/www" ]; then
 ln -s /tmp/usage.htm /www/usage.htm
fi

exit 0
